TITLE="Программирование на Python от Биджа"
SUBTITLE="Для начинающих"
AUTHOR='Брайн “Beej Jorgensen” Холл'
VERSION_DATE="Версия 0.0.12, Авторские права © 8 февраля 2025"

GUIDE_ID=bgpython

#BGBSPD_BUILD_DIR?=../../bgbspd
BGBSPD_BUILD_DIR?=../bgbspd-main

WEB_IMAGES=$(wildcard *.png *.svg)

include $(BGBSPD_BUILD_DIR)/source.make
